### ISSUE TITLE
iterate through xml children?

### ISSUE THREAD

**Issue by hopewise** [massiveinteractive/mloader#30]
I tried to iterate though children of loaded xml:

    var xml = event.target.content.firstElement();

then, I tried `for (child in xml.nodes)`, `for (child in xml.children)`, `for (child in xml.elements)`

nothing worked.. can you please provide little example?
thanks

**Comment by elsassph** [comment]
There is an example in the `XmlLoader` source:
https://github.com/massiveinteractive/mloader/blob/master/src/mloader/XmlLoader.hx

**Comment by hopewise** [comment]
oh! I had to access elements as a function! I will try when I get home, thanks
by the way, nice profile photo!
